#! /usr/bin/env ruby

"""
this is a tool for submitting remote jobs through the basic ssh tool
version v1.0
# Features
- remote single job submitting by:
`rjob -u <user> -p <path> '<cmd>'`
- remote multiple job submitting by a command file:
`rjob -u <user> -p <path> -c <cmdfile>`
*about the command file*
the command file is simply a collection of commands that separated by ';', and only the previous command executed successfully
then can next command being executed, or else the execution will stop immediated
- remote runing a shell file as command:
`rjob -u <user> -p <path> -s <shellfile>`
#TBD, currently not supported
- setup user,password,host
`rjob -`
# Strategy
- need consider the password entering question
"""

if ENV.has_key?('RUBY_LIB')
	splitted=ENV['RUBY_LIB'].split(':');
	splitted.each do |s|
		$LOAD_PATH << s;
	end
end
#puts $LOAD_PATH
#require 'rhload';
$toolhome = File.dirname(File.absolute_path(__FILE__));
$LOAD_PATH << $toolhome;

require_relative 'lib/mainentry.rb';

e = MainEntry.new();
$SIG = e.run();
## puts "program exists with sig: #{$SIG}";
exit $SIG;
